apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-architect-app
  namespace: aws-architect
  labels:
    app: aws-architect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aws-architect
  template:
    metadata:
      labels:
        app: aws-architect
    spec:
      containers:
      - name: aws-architect
        image: aws-architect:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: aws-architect-config
              key: NODE_ENV
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-architect-config
              key: AWS_REGION
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: aws-architect-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: aws-architect-secrets
              key: DATABASE_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-architect-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-architect-secrets
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false