apiVersion: v1
kind: Secret
metadata:
  name: aws-architect-secrets
  namespace: aws-architect
type: Opaque
stringData:
  DATABASE_URL: "postgresql://username:password@host:5432/database"
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
---
# Note: Replace the above values with actual credentials before deploying
# You can also use AWS Secrets Manager or External Secrets Operator for better security